apiVersion: v1
kind: Service
metadata:
  name: blueblocks-xyz
  namespace: consumer-sites
  labels:
    app: blueblocks-xyz
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: blueblocks-xyz
